[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[[constraint]]
  name = "github.com/docker/cnab-to-oci"
  source = "github.com/radu-matei/cnab-to-oci"
  branch = "canonical"

[[constraint]]
  name = "github.com/in-toto/in-toto-golang"
   source = "github.com/radu-matei/in-toto-golang"
   branch = "inspections-dir"

[[override]]
  name = "github.com/containerd/containerd"
  revision = "7c1e88399ec0b0b077121d9d5ad97e647b11c870"

[[override]]
  name = "github.com/containerd/cgroups"
  revision = "4994991857f9b0ae8dc439551e8bebdbb4bf66c1"

[[override]]
  name = "github.com/docker/distribution"
  revision = "0d3efadf0154c2b8a4e7b6621fff9809655cc580"

[prune]
  go-tests = true
  unused-packages = true
