[[constraint]]
  name = "github.com/in-toto/in-toto-golang"
   source = "github.com/radu-matei/in-toto-golang"
   branch = "inspections-dir"

[[constraint]]
  name = "github.com/deislabs/cnab-go"
  version = "v0.7.1-beta1"

[[constraint]]
  name = "github.com/docker/cnab-to-oci"
  #version = "v0.7.1-beta1"
  source = "github.com/eunomie/cnab-to-oci"
  branch = "cli-bump"

[[constraint]]
  name = "github.com/containerd/containerd"
  version = "v1.3.0"

[[override]]
  name = "github.com/docker/distribution"
  #version = "v2.7.1"
  revision = "0d3efadf0154c2b8a4e7b6621fff9809655cc580"

[[override]]
  name = "github.com/docker/docker-credential-helpers"
  version = "v0.6.3"

[prune]
  go-tests = true
  unused-packages = true
